version: '3.8'

services:
  database:
    container_name: pdw-database
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./.data/database:/var/lib/postgresql/data
      - ./.data/init-database.sql:/docker-entrypoint-initdb.d/database.sql

  backend:
    container_name: pdw-backend
    build: ./backend
    ports:
      - 5000:3000
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    environment:
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - DB_HOST=database
      - DB_PORT=${POSTGRES_PORT}
      - DB_NAME=${POSTGRES_DB}

  frontend:
    container_name: pdw-frontend
    build: ./frontend
    ports:
      - 6000:3000
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000