version: '3.8'

services:
  database:
    container_name: pdw-database
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=pdw
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./.data/database:/var/lib/postgresql/data
      - ./.data/init-database.sql:/docker-entrypoint-initdb.d/database.sql

  backend:
    container_name: pdw-backend
    build: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=pdw

  frontend:
    container_name: pdw-frontend
    build: ./frontend
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      - NODE_ENV=development
      - API_URL=backend
      - API_PORT=3000